//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maverick.PCF.Builder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pcf.gallery/pcfbuilder.json")]
        public string PcfGalleryTemplateUri {
            get {
                return ((string)(this["PcfGalleryTemplateUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bdd1339a-cc2f-4568-b061-7a7fcc3f5597")]
        public string AppInsightsInstrumentationKey {
            get {
                return ((string)(this["AppInsightsInstrumentationKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://app.powerbi.com/view?r=eyJrIjoiZTY4N2E1ODQtZWQ5Ny00NjJmLWI5OTctNjIwYmU5MG" +
            "UxMjNjIiwidCI6IjMxYzIwYTIzLTJlZDItNDY4ZC1iYWFiLTQyZWRmOTk4MTI4YiIsImMiOjF9")]
        public string AppInsightsPowerBiReport {
            get {
                return ((string)(this["AppInsightsPowerBiReport"]));
            }
        }
    }
}
